### ISSUE TITLE
Introduction text 

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/userstories#2]
## Value Proposition

**As a** user

**I need** understand the purpose of the website 

**to be able to** interact with the wizard

## Description

![Bildschirmfoto 2022-12-09 um 14 32 35](https://user-images.githubusercontent.com/96984853/206713694-8928f2e7-15a2-4d06-9bf6-3a315196e953.png)

## Acceptance Criteria
- [ ] On the main page is a short headline and a 
- [ ] description of the web page
-- [ ] the content is: "..." 
- [ ] there are 3 icons explaining the benefits of movie flip 
-- [ ] the content is: "..." 

## Tasks

- [ ] the Poppins Font is downloaded and fully integrated https://fonts.google.com/specimen/Poppins
- [ ] the icons are attached as a svg. Intregation guide: https://blog.logrocket.com/how-to-use-svgs-in-react/
- [ ] 
![clarity_bullseye-line](https://user-images.githubusercontent.com/96984853/206715779-856bd0c7-dd00-4717-8012-ab5054a81370.svg)

![clarity_clock-line](https://user-images.githubusercontent.com/96984853/206715853-8127a847-641d-4fc9-9724-c98ef7c145f5.svg)
![clarity_happy-face-line](https://user-images.githubusercontent.com/96984853/206715885-275a7b7c-625d-490e-89ad-712a5e4c8ed6.svg)
