### ISSUE TITLE
Wizard | Question 1 - movie duration 

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/userstories#3]
## Value Proposition

**As a** user

**I need** to select the length of the movie 

**to be able to** to find the running time suitable for my time 

## Description
	
![Bildschirmfoto 2022-12-09 um 14 58 59](https://user-images.githubusercontent.com/96984853/206718757-a38bfa9b-4e7e-4d03-9e8d-9b00d9ec966b.png)

## Acceptance Criteria
- [ ] There is a headline saying "Wie lange darf dein Film heute sein?"
- [ ] The user can choose between four options:  "möglichst kurz, normale Lauflänge, ich habe Zeit, ist mir egal"
- [ ]  After clicking the button the user will be redirected to the movie recommendation page, where a movie title with the running length is shown (no further styling) 

## Tasks
- [ ] every question is located in a wizard parent component (app > main > wizard > questionDuration)
- [ ] for the beginning the array method is used to search a test movie array with 5 movies
- [ ] the test movie array is located in a lib folder  
- [ ] the runtime is calculated on the duration field: - möglichst kurz (<100 Min), normale Lauflänge (100 - 140 Min), ich habe Zeit (>140 Min), ist mir egal (every movie)  
- [ ] after hitting one of the four options, the user is redirected to a dynamic URL, which is rendered by the movie slug or ID
