### ISSUE TITLE
Moviedetailpage | Basic Styling 

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/userstories#4]
## Value Proposition

**As a** user

**I need** have to see the basic information to the recommended movie  

**to be able to** have an idea if I want to watch it 

## Description

![Bildschirmfoto 2022-12-09 um 15 15 06](https://user-images.githubusercontent.com/96984853/206721638-5a960048-aff7-4070-851c-24329165599f.png)

## Acceptance Criteria

- [ ] The following content is shown: 
- [ ] a movie poster (not clickable) 
- [ ] a headline (max 2 rows)
- [ ] tags with information about the duration and genre 
- [ ] a movie description which is folded in (as default - max 200 characters) and can be unfolded by click (all characters)

## Tasks

(for developers team)

- [ ] the movie poster is linking to an external URL 
- [ ] tags are different Key/value pairs, but have the same stying (duration = duration, genre = genre array)
- [ ] the "read more" button is a useState with the status true/false

**Comment by marvinRoellecke** [comment]
Philip, schöne neue erste User Story ;)

Vielleicht kannst du in deiner Grafik (das Design ist mega) noch kenntlich machen, dass Footer, Bookmark Button, etc. noch nicht teil dieser User Story sind.

**Comment by julialoeschel** [comment]
Hey :) 
sehr schön, das ist eine wunderbare erste Story! 
...das was Marvin sagt, im Scribble solte nur drin sein, was auch wirklich teil der US ist. 

Ich sehe diese "...more" funktion mit dem ausklappen als eigene klitzekleine US, die man schön unabhngig vom Rest auch zwischendurch mal erledigen könnte (aber nicht muss) .
Du könntest die auslagern, wenn du möchtest. 
So würde ich das aber auch akzeptieren :) 

:octocat:

**Comment by flipkoehler** [comment]
yeah! Danke euch für das Feedback. Hab das Design neu hinterlegt :) 

zu der "...more" Funktion. Vielleicht hab ich da schon heimlich was gebastelt am Wochenende 🙃
