### ISSUE TITLE
About Page & Navigation 

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/userstories#6]
## Value Proposition

**As a** user 

**I need** further information about movie flip 

**to be able to** understand the project

## Description
![Bildschirmfoto 2022-12-09 um 15 50 38](https://user-images.githubusercontent.com/96984853/206728609-883cde5e-914f-427e-8c24-ce6a79272a45.png)

## Acceptance Criteria

- [ ] there is a navigation at the bottom of the page, where I can choose between the main page and the about page
- [ ] the icon of the active page has an underline 
- [ ] on the detail page is a headline saying "Über Movie Flip" and an icon 
- [ ]  

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
